apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ready-example
spec:
  selector:
    matchLabels:
      app: app-ready-example
  replicas: 1
  template:
    metadata:
      labels:
        app: app-ready-example
    spec:
      containers:
      - name: app-ready-example
        image: app-adv-check:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          successThreshold: 3
          httpGet:
            path: /ready_check
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 10
