
apiVersion: v1
kind: Namespace
metadata:
  name: demospace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloservice
  namespace: demospace
  labels:
    app: helloservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloservice
  template:
    metadata:
      labels:
        app: helloservice
    spec:
      containers:
      - env:
        - name: PORT
          value: "9000"
        image: ghcr.io/podtato-head/podtatoserver:v0.1.1
        imagePullPolicy: Always
        name: server
        ports:
        - containerPort: 9000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: helloservice
  namespace: demospace
  labels: 
    app: helloservice
spec:
  selector:
    app: helloservice
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  type: NodePort