apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: nginx
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        chaos: blast-here
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shine-on-you-crazy-diamond
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cant-touch-dis
  template:
    metadata:
      labels:
        app: cant-touch-dis
    spec:
      containers:
      - image: nginx
        name: nginx