kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: demospace
  name: account-demospace-manager-ojdiz

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: demospace
  name: role-demospace-manager-ojdiz
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["chaos-mesh.org"]
  resources: [ "*" ]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-demospace-manager-ojdiz
  namespace: demospace
subjects:
- kind: ServiceAccount
  name: account-demospace-manager-ojdiz
  namespace: demospace
roleRef:
  kind: Role
  name: role-demospace-manager-ojdiz
  apiGroup: rbac.authorization.k8s.io
